controller_manager:
  ros__parameters: 
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    omni_wheel_drive_controller: 
      type: velocity_controllers/JointGroupVelocityController

joint_state_broadcaster:
  ros__parameters:
    {}

omni_wheel_drive_controller:
  ros__parameters: 
    joints: 
      - left_wheel_joint
      - rear_wheel_joint
      - right_wheel_joint
    interface_name: velocity
